### ISSUE TITLE
Light, Medium and Heavy seem to be identical

### ISSUE THREAD

**Issue by arzg** [bouncetechnologies/Font-Smoothing-Adjuster#16]
I’m running on macOS 11.5.2 (20G95) with TextEdit 1.16 (365.2).

---
Disabled:
<img width="698" alt="0" src="https://user-images.githubusercontent.com/31783266/133038903-12d2c52f-ba3e-41f1-9d80-0915e2b2d9f0.png">

---
Light:
<img width="698" alt="1" src="https://user-images.githubusercontent.com/31783266/133038928-f97763ed-877d-4619-9711-6d583a044735.png">

---
Medium:
<img width="698" alt="2" src="https://user-images.githubusercontent.com/31783266/133038932-bd44d957-41e5-4ba4-97e5-51e21f975371.png">

---
Heavy:
<img width="698" alt="3" src="https://user-images.githubusercontent.com/31783266/133038936-1a1f00b2-bf9d-4057-9ae8-019426244193.png">

---

I ran the last three through an image diff tool, with no differences found. I haven’t tested this with any apps other than TextEdit, but I doubt it’s TextEdit-specific since I didn’t notice any change anywhere in the OS while switching between the last three modes, and I’d assume TextEdit uses the native macOS drawing APIs anyway. Here’s a little comparison I made with the value of `AppleFontSmoothing` below:

<img width="736" alt="Screen Shot 2021-09-13 at 5 19 55 pm" src="https://user-images.githubusercontent.com/31783266/133040610-78e91514-7e11-45a1-ac5e-897ac0b8a072.png">

**Comment by abyrne10** [comment]
Hi @arzg, thank you for flagging this up, and for your detailed description of the issue. I can confirm that I experience the same issue on TextEdit and other apps on 11.5.2, namely that while disabling font smoothing has a noticeable effect, there seems to be no difference between light, medium and heavy font smoothing.

I've confirmed that Font Smoothing Adjuster is setting the correct user defaults preferences on my machine, so I'm assuming that a recent update of macOS has changed how those settings are interpreted by apps. I'll look at filing a bug report with Apple, and post here with any response that I get.

**Comment by arzg** [comment]
Just to clarify, were all four options working individually recently (say, on Catalina)? If not, then I think this might actually be an intended behaviour, since all four options used to be displayed as a drop-down menu in System Preferences many versions ago.

**Comment by abyrne10** [comment]
I just tested on Catalina (10.15.5 - the oldest version of macOS I currently have access to), and after running the results through an image diffing tool it's clear that there's no difference between the light, medium and heavy font smoothing settings. I suppose this makes sense, as Catalina only has a checkbox for using font smoothing when available.

In any case, thanks for pointing this out, we'll ship an update to the app making it a straight toggle between enabling and disabling font smoothing 👍

**Comment by jspiro** [comment]
I thought I was losing my eyesight with the lower PPI on MBPs than iPhones. This makes things SO much clearer. Thank you!
