### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by RuanPienaarCode** [bouncetechnologies/Font-Smoothing-Adjuster#17]
Hi, thanks for trying to fix scaling issue. 
I  installed the app and set it to heavy. I rebooted the macbook.
After the reboot it shows a transparent box in the top left corner of my screen, I set the settings back to default.
Restarted and the transparent box was still there.
I then uninstalled the app and restarted and now this transparent is still there.

Any idea what it could be and how to fix this.

Thank you

**Comment by abyrne10** [comment]
Hi @RuanPienaarCode, thanks for getting in touch. Please could you post a screenshot of what you're seeing to help me understand the issue? And please could you also post the output of running:

```
defaults -currentHost read -g AppleFontSmoothing
```

in your terminal?

**Comment by abyrne10** [comment]
Hi @RuanPienaarCode, have been able to reproduce this? If not, I'll close the issue for now.
