### ISSUE TITLE
Won't allow user to quit application after "The operation couldn't be completed" error 

### ISSUE THREAD

**Issue by ninjarogue** [bouncetechnologies/Font-Smoothing-Adjuster#36]
This is really sketchy.. for some reason there was an error after I hit the enable button and all of sudden I was not allowed to quit the application

**Comment by abyrne10** [comment]
Hi @ninjarogue, I'm sorry you experienced this issue, thank you for raising it with us. I'll look into it and try to reproduce it.

**Comment by abyrne10** [comment]
May I also ask what version of macOS you are using, and what version of the Font Smoothing Adjuster app?
