### ISSUE TITLE
Error when using first time

### ISSUE THREAD

**Issue by hisaac** [bouncetechnologies/Font-Smoothing-Adjuster#8]
I'm getting an error when I try to use Font Smoothing Adjuster for the first time.

https://user-images.githubusercontent.com/923876/108141737-e7663e00-7089-11eb-9e5f-0aeb60e459eb.mov

This has happened on both of my computers, both running macOS 11.2.1.

After running one of the defaults commands in the readme, such as:

```shell
defaults -currentHost write -g AppleFontSmoothing -int 0
```

Then when I re-open Font Smoothing Adjuster, the app works as expected.

**Comment by abyrne10** [comment]
Hi @hisaac, thank you for pointing this out, and sorry the app wasn't working for you. The issue was that in the latest release I wasn't properly handling the case where the AppleFontSmoothing wasn't set. I've now fixed this in #9, and will release an app update shortly.

**Comment by abyrne10** [comment]
This issue is now fixed in [Release v1.1.1](https://github.com/bouncetechnologies/Font-Smoothing-Adjuster/releases/tag/v1.1.1). You can download the updated app from the release page, or use the "Check for updates..." menu item to automatically download and install this version. Cheers!
